import json
import math
import time
import requests
import os
import re
import sys
import traceback
import hashlib
from datetime import datetime

# Shared Head/Face contract (constants + gesture math — single tuning surface)
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__))))
import head_cmds as hc

BASE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
WORLD_STATE_PATH = os.path.join(BASE_DIR, "shared_state", "Worldstate.json")
STRATEGY_PATH = os.path.join(BASE_DIR, "shared_state", "current_strategy.json")
PROMPT_PATH = os.path.join(BASE_DIR, "ai_tactics", "system_prompt.txt")
FRAGMENTS_DIR = os.path.join(BASE_DIR, "strategy", "fragments")
SCENARIO_PATH = os.path.join(BASE_DIR, "ai_tactics", "active_scenario.json")

# FIX 1: Harte Bindung an natives lokales IPv4
OLLAMA_URL = os.getenv("R2K_OLLAMA_URL", "http://127.0.0.1:11434/api/generate")
MODEL_NAME = os.getenv("R2K_OLLAMA_MODEL", "qwen2.5-coder:3b")

# --- Phase 1 instrumentation: LLM trace logger ---
RUN_ID = os.getenv("R2K_RUN_ID", f"run_{int(time.time())}")
LOG_DIR = os.path.join(BASE_DIR, "logs")
LLM_TRACE_PATH = os.path.join(LOG_DIR, f"llm_trace_{RUN_ID}.jsonl")
os.makedirs(LOG_DIR, exist_ok=True)

# --- Phase 2.5b: Dynamic prompt injection ---
# Ollama is stateless — it receives the `system` field in every /api/generate call
# and doesn't cache it. We can change sys_prompt between calls without restarting.
# This assembles the prompt from fragments based on (match_state.status, mode),
# caching by tuple to avoid re-reading files every 20ms poll.
_prompt_cache = {}  # (status, mode) -> assembled prompt string
_active_mode = None  # determined once at startup from active_scenario.json
_active_n_blue = 3  # number of blue bots, derived from mode

# --- Phase I (C3 inter-lingua): text transform mode ---
# R2K_TEXT_MODE=1 replaces the JSON min_ents world encoding with a condensed
# text transform in dictionary vocabulary, and expects text-line output
# ("blue_1 move to (2.2, 0.3)") instead of JSON. Env-gated so K2 can A/B
# both encodings without code changes. Default 0 = current JSON behavior.
TEXT_MODE = os.getenv("R2K_TEXT_MODE", "0") == "1"

def _n_blue_from_mode(mode):
    """Derive number of blue bots from mode string (e.g. '2vs2' -> 2, '3vs3' -> 3)."""
    try:
        return int(mode.split('vs')[0])
    except (ValueError, IndexError):
        return 3

def _text_output_header(n_blue):
    """Build the text-mode output header with the correct bot count."""
    bot_names = ", ".join(f"blue_{i+1}" for i in range(n_blue))
    return (
        f"Output exactly one line per blue bot in the INPUT above ({bot_names}). "
        f"Never use the same bot twice. Format: 'blue_1 move to (X, Y)', "
        f"'blue_1 kick', 'blue_1 pass to (X, Y)', 'blue_1 clear the ball', "
        f"'blue_1 cover the goal line at (-4.0, Y)', or "
        f"'blue_1 hold position'. Use the positions from the INPUT. "
        f"Do NOT copy example coordinates."
    )
TEXT_EXPLAIN_INSTRUCTION = (
    "Start with 'ANALYSIS: <assessment>', then 'ORACLE: <prediction>', "
    "then one line per blue bot."
)

# --- Demo mode: sequence-based waypoint tracking (per-bot, A2bot scope 1) ---
# Waypoints are loaded from shared_state/waypoints.json (generated by the
# compiler at startup or interactively via task_input.json). The evaluator
# tracks the current target label per bot, detects arrival, and injects the
# labels into the user prompt. The LLM does pure string→coordinate lookup.
DEMO_DEFAULT_BOT = "blue1"
DEMO_ARRIVAL_DIST = 0.5    # bot within this distance → advance to next WP
DEMO_PARK_DIST = 0.2       # final WP: within this → park (stop re-issuing the Move)
DEMO_START_POS_DEFAULT = (0.0, 0.0)

# === Calib mode (R2K_CALIB=1): direct hardware addressing, field-first ===
# Naming: y1/y2 = Yahboom (physical, µROS topics stay /blue_N/cmd_vel),
# k1 = Booster K1, blue1..3 = Gazebo sim. Relay keys are the user identity.
CALIB = os.getenv('R2K_CALIB') == '1'
# Mode merge (2026-09-08): calib = routing-only field stack — no 3B
# executor cycles, no Worldstate dependency, one writer per command.
# --nosim is a launcher alias of --calib.
# bot -> {"waypoints": [...], "target_idx": 0, "stopped_idx": 0,
#         "arrival_time": 0, "start_pos": None}
_demo_state = {}
WAYPOINTS_PATH = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                              'shared_state', 'waypoints.json')
TASK_INPUT_PATH = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                                'shared_state', 'task_input.json')
_last_task_mtime = 0
# DAMP hint state (calib): armed by first k1 Goto; fires once if odom is
# fresh but position hasn't moved after K1_DAMP_HINT_SECS.
_k1_damp_hint_armed = False
_k1_damp_hint_fired = False
_k1_goto_t0 = 0.0
_k1_goto_start = None
K1_DAMP_HINT_SECS = 3.0
K1_DAMP_HINT_MIN_MOVE_M = 0.05   # position must shift at least this much


def _calib_damp_hint_tick():
    """Check if K1 hasn't moved within K1_DAMP_HINT_SECS after Goto.
    Fires ONCE per session — warns about DAMP mode, not absence or crash."""
    global _k1_damp_hint_armed, _k1_damp_hint_fired
    if not _k1_damp_hint_armed or _k1_damp_hint_fired:
        return
    if time.time() - _k1_goto_t0 < K1_DAMP_HINT_SECS:
        return
    _k1_damp_hint_armed = False
    try:
        with open(WAYPOINTS_PATH.replace('waypoints.json', 'k1_odom.json')) as f:
            o = json.load(f)
        dx = o.get('x', 0.0) - (_k1_goto_start[0] if _k1_goto_start else 0.0)
        dy = o.get('y', 0.0) - (_k1_goto_start[1] if _k1_goto_start else 0.0)
        dist_moved = math.hypot(dx, dy)
        if dist_moved < K1_DAMP_HINT_MIN_MOVE_M:
            print(f"⚠ K1 DAMP HINT: Goto sent but k1 didn't move in "
                  f"{K1_DAMP_HINT_SECS}s — DAMP mode active? (odom fresh, "
                  f"position unchanged)", flush=True)
            _k1_damp_hint_fired = True
        else:
            _k1_damp_hint_armed = False  # moved fine — no hint needed
    except Exception:
        pass

DEMO_BOT_PREFIX_RE = re.compile(r'^(blue_?\d+|y_?\d+|yahboom_?\d+|k1_bot|k1)\b[:,]?\s*(.+)$')
DEMO_SCOPE_TOKEN_RE = re.compile(r'^\(?\s*(all|every|both|yahbooms?|sim(?:ulated)?)\b[\s,:\)-]*')
DEMO_SCOPE_BOTS_RE = re.compile(r'^bots?\b[\s,:-]*')
DEMO_COORD_RE = re.compile(
    r'^(?:go(?:\s*to)?|goto|move(?:\s*to)?|drive(?:\s*to)?)\s*[\(\[]?\s*'
    r'(-?\d+(?:\.\d+)?)\s*[,; ]\s*(-?\d+(?:\.\d+)?)\s*[\)\]]?$')
DEMO_TASK_VERB_RE = re.compile(
    r'\b(go\s*to|goto|move|drive|patrol|draw|trace|approach|return|circle|'
    r'line\s*up|square|triangle|rectangle|pentagon|hexagon|stop|halt|break|'
    r'exit|resume|continue|restart|redo|repeat|home)\b')
DEMO_FAST_STOP = ("stop", "break", "exit", "halt")
DEMO_FAST_RESUME = ("resume", "continue")
DEMO_FAST_RESTART = ("restart", "re-start", "redo", "repeat")
DEMO_FAST_HOME = ("go home", "return", "return to start", "go to start", "home")
DEMO_CONTROL_VERBS = frozenset(DEMO_FAST_STOP + DEMO_FAST_RESUME +
                               DEMO_FAST_RESTART + DEMO_FAST_HOME)

DEMO_COMPILER_MODEL = "qwen2.5:7b"

# --- Demo head/face routing (calibration showcase) ---
# ALL bare commands default to blue_1 (uniform mental model, user 2026-09-06):
# blue_1 = primary showcase bot (physical yes/no via chassis body gestures,
# face via body turn, K1 head via mirror slot); camera gimbal work = explicit
# 'blue_2 ...' prefix (Y#2 carries the PTZ; Y#1 has none).
DEMO_HEAD_DEFAULT_BOT = "blue1"  # bare say → Y1 body gesture (bridge fork)
DEMO_FACE_DEFAULT_BOT = "blue1"
DEMO_HEAD_K1_ALIASES = ("k1_bot", "k1")
# K1 calibration Goto — same raw values but separate tuple (documents the
# different routing semantics vs head/face aliases that remap to blue1).
DEMO_K1_ALIASES = ("k1_bot", "k1")
# Closed-loop Goto routing (odom feedback, bridge-side loop): k1 + yahbooms.
# Yahboom (2026-09-08) = K1 field-test rehearsal — same CLI/exec/log flow,
# coarse ±30% encoder-odom arrival accepted by design.
DEMO_GOTO_BOTS = ("k1_bot", "k1", "y1", "y2")
# Yahboom calib aliases → relay key (y1/y2). Legacy spellings accepted.
CALIB_Y_ALIASES = {"y1": "y1", "y_1": "y1", "yahboom1": "y1", "yahboom_1": "y1",
                   "yahboom #1": "y1",
                   "y2": "y2", "y_2": "y2", "yahboom2": "y2", "yahboom_2": "y2",
                   "yahboom #2": "y2"}
# TimedMove defaults (kept in sync with ollama_sandbox_bridge.py constants
# by convention: same names, same values — the evaluator needs them to
# compute duration_s at parse time).
Y_CALIB_VX = 0.2      # m/s
Y_CALIB_VYAW = 0.5    # rad/s (+ = CCW)
# Calib 'say no' on the gimbal-less Yahboom: a Seq of arrival-latched
# relative Faces (the PROVEN turn machinery), not an oscillating vyaw —
# live 2026-09-08: ±45° @ 1Hz still cancelled in the board yaw PID (0.5s
# reversals), while sustained closed-loop turns at the same cap work.
# Each step physically completes; slow but visible.
CALIB_SAYNO_SHAKE_AMP_DEG = 20.0   # per-swing amplitude — smaller = higher
                                    # shake frequency at the same cap (user:
                                    # "frequency too low" 2026-09-08; with the
                                    # 1.2 rad/s cap each swing ≈ 0.6-0.7s)
CALIB_SAYNO_SHAKE_CYCLES = 2       # full left-right cycles
DEMO_HEAD_LOOK = {
    "look left": (hc.LOOK_PAN_DEG, 0.0),
    "look right": (-hc.LOOK_PAN_DEG, 0.0),
    "look center": (0.0, 0.0),
    "look straight": (0.0, 0.0),
    "look up": (0.0, hc.LOOK_TILT_UP_DEG),
    "look down": (0.0, -hc.LOOK_TILT_DOWN_DEG),
}
DEMO_HEAD_GESTURES = {"say yes": "yes", "say no": "no"}
# Face (body yaw) — absolute compass/field directions (blue attacks +X, left = +Y)
DEMO_FACE_ABS = {
    "face north": math.pi / 2,          # +Y
    "face south": -math.pi / 2,         # -Y
    "face east": 0.0,                   # +X, toward opponent goal
    "face west": math.pi,               # -X, toward own goal
    "face opponent goal": 0.0,
    "face own goal": math.pi,
    "face left": math.pi / 2,
    "face right": -math.pi / 2,
}
# CALIB boot compass (user convention 2026-09-08): power-cycle the bot AT
# the home mark, NOSE FACING NORTH — the odom frame boots at (0,0,yaw 0),
# so yaw 0 = north = the natural rest orientation. East is 90° clockwise
# from north = -π/2 (ROS yaw is CCW-positive). Demo mode keeps the world
# frame above (sim twins spawn with yaw 0 = +X = east).
DEMO_FACE_ABS_CALIB = {
    "face north": 0.0,
    "face east": -math.pi / 2,
    "face south": math.pi,
    "face west": math.pi / 2,
    "face opponent goal": -math.pi / 2,   # calib ritual: nose north, field east
    "face own goal": math.pi / 2,
    "face left": math.pi / 2,
    "face right": -math.pi / 2,
}
DEMO_TURN_REL = {
    "turn left": math.pi / 2,
    "turn right": -math.pi / 2,
    "turn around": math.pi,
}
DEMO_ROTATE_RE = re.compile(r'^rotate\s+(-?\d+(?:\.\d+)?)\s*(?:deg(?:rees)?)?$')
WP_MERGE_EPS_M = 0.1             # consecutive waypoints within this distance
                                 # are ONE waypoint (pause merge)
# --- Sequences: "face west, then go to (1,1)" (one bot per chain, user rule) ---
# "then"/"next" chain FAST-PATH steps sequentially; "; " stays PARALLEL
# clauses (independent). The BRIDGE owns step execution (yaw/position/time
# are only fully observable there) — the evaluator just translates.
DEMO_CHAIN_SPLIT_RE = re.compile(r',?\s*\b(?:then|next)\b\s+')
DEMO_PAUSE_STEP_RE = re.compile(
    r'^(?:pause|wait)\s+(\d+(?:\.\d+)?)\s*(?:s|sec|secs|seconds?)?$')
# Instant-command words that must never reach the 7B compiler (it would
# guess coordinates for facing/head parts of a compound)
DEMO_INSTANT_WORD_RE = re.compile(
    r'\b(?:face|turn|rotate|look|say)\b')

# Comma-only separator (UNLESS followed by digit — coordinate guard, or by
# "then"/"next" — chain guard). Each sub-clause is routed independently.
# This makes "stop, resume" two independent control verbs instead of a single
# compile task, while "go to 1, 1, then go to 2, 2" stays a single chain.
_DEMO_COMMA_SEP_RE = re.compile(r',\s+(?!\d)(?!(?:then|next)\b)')


def _chain_step(text):
    """One fast-path step -> Seq step dict, or None if not chain-able.
    POSITION-MOVING steps (coordinate moves) are deliberately NOT chain-able:
    drag_twin only recognizes plain waypath Move targets (drag_twin.py
    _refresh_targets) — chained moves made its idle-watch false-positive on
    commanded drives (stop + teleport-back + goto loop, 2026-09-05 rewind).
    Chains are non-motion steps only; run go-to as its own command."""
    text = text.strip()
    m = DEMO_PAUSE_STEP_RE.match(text)
    if m:
        return {"action": "Pause", "duration": float(m.group(1))}
    if text in DEMO_FACE_ABS:
        return {"action": "Face", "yaw": DEMO_FACE_ABS[text]}
    if text in DEMO_TURN_REL:
        return {"action": "Face", "relative_angle": DEMO_TURN_REL[text]}
    if text in DEMO_HEAD_LOOK:
        pan, tilt = DEMO_HEAD_LOOK[text]
        return {"action": "Head", "pan_deg": pan, "tilt_deg": tilt}
    if text in DEMO_HEAD_GESTURES:
        return {"action": "Head", "gesture": DEMO_HEAD_GESTURES[text],
                "cycles": hc.GESTURE_CYCLES}
    m = DEMO_ROTATE_RE.match(text)
    if m:
        return {"action": "Face", "relative_angle": math.radians(float(m.group(1)))}
    return None


def _chain_move_segment(text):
    """One move-chain segment -> {'kind': 'move'|'pause', ...} or None.
    Move-chains flatten to WAYPOINTS (the proven machinery — drag_twin's
    watch sees the 3B's plain Move targets; chained Seq-moves caused the
    teleport loop, rewound 2026-09-05). 'goto' == 'go to' (DEMO_COORD_RE)."""
    text = text.strip()
    m = DEMO_PAUSE_STEP_RE.match(text)
    if m:
        return {"kind": "pause", "duration": float(m.group(1))}
    m = DEMO_COORD_RE.match(text)
    if m:
        return {"kind": "move", "x": float(m.group(1)), "y": float(m.group(2))}
    return None


def _demo_waypath_chain(bot, move_segs, ents):
    """Flatten a move+pause chain into a waypath and seed it (proven arrival
    /hold/park machinery). Pauses attach to the PRECEDING waypoint's
    hold_duration; a leading pause holds at the bot's current position."""
    st = _demo_bot_state(bot)
    st["target_idx"] = 0
    st["arrival_time"] = 0
    st["fast_cmd"] = None
    wps = []
    for seg in move_segs:
        if seg["kind"] == "pause":
            if wps:
                wps[-1]["hold_duration"] += seg["duration"]
            else:
                # leading pause: hold in place first (current position)
                bv = ents.get(bot) or {"x": 0.0, "y": 0.0}
                wps.append({"label": "HOLD", "x": float(bv["x"]),
                            "y": float(bv["y"]), "hold_duration": seg["duration"]})
        else:
            wps.append({"label": "WP", "x": seg["x"], "y": seg["y"],
                        "hold_duration": 0.0})
    st["waypoints"] = _merge_duplicate_waypoints(_norm_demo_waypoints(wps))
    _write_waypoints_file()
    descr = " -> ".join(
        f"({w['x']:g},{w['y']:g})" + (f" [{w['hold_duration']:g}s]"
                                      if w["hold_duration"] else "")
        for w in st["waypoints"])
    print(f"⚡ [{bot}] waypath chain: {descr} (auto-park)", flush=True)


def _step_label(step):
    sa = step.get("action")
    if sa == "Pause":
        return f"pause {step['duration']}s"
    if sa == "Face":
        return "turn" if "relative_angle" in step else "face"
    if sa == "Move":
        return f"go to ({step['x']:g},{step['y']:g})"
    if sa == "Head":
        return f"say {step['gesture']}" if "gesture" in step else "look"
    return sa


def _demo_seq_cmd(bot, steps):
    """Write a one-bot sequence: the bridge executes the steps in order
    (its cursor advances on face-arrival / move-arrival / time) and parks
    at the end. fast_cmd authority keeps the executor away from the bot."""
    cmd = {"action": "Seq", "id": time.time(), "steps": steps}
    _demo_set_fast_cmd(bot, cmd,
                       "Seq: " + " -> ".join(_step_label(s) for s in steps))
# Heading-relative movement ("move forward 1m") is UNSUPPORTED: no bot yaw in
# Worldstate (v7 Task 3a) and the 7B compiles it to garbage coordinates
# (live: "forward 1m" became a ~2.3m diagonal run). Reject with guidance.
DEMO_HEADING_REL_RE = re.compile(r'\b(forward|forwards|backward|backwards|ahead)\s+\d')

DEMO_LANDMARKS = {
    "center": (0.0, 0.0),
    "left wing": (2.0, 2.5),
    "right wing": (2.0, -2.5),
    "wing": (2.0, 2.5),
    "own goal": (-4.5, 0.0),
    "opponent goal": (4.5, 0.0),
    "own left corner": (-4.5, 3.0),
    "own right corner": (-4.5, -3.0),
    "opponent left corner": (4.5, 3.0),
    "opponent right corner": (4.5, -3.0),
    "corner": (-4.5, 3.0),
    "left corner": (-4.5, 3.0),
    "right corner": (-4.5, -3.0),
}

# START position — captured per bot at first sight in the world state

def _demo_bot_state(bot):
    st = _demo_state.get(bot)
    if st is None:
        st = {"waypoints": [], "target_idx": 0, "stopped_idx": 0,
              "arrival_time": 0, "start_pos": None, "fast_cmd": None}
        _demo_state[bot] = st
    return st

def _demo_start_pos_of(bot):
    st = _demo_bot_state(bot)
    return st["start_pos"] if st["start_pos"] else DEMO_START_POS_DEFAULT

def _norm_demo_waypoints(wps):
    return [{"label": w["label"], "x": float(w["x"]), "y": float(w["y"]),
             "hold_duration": float(w.get("hold_duration", 0))} for w in wps]


def _merge_duplicate_waypoints(wps, eps=WP_MERGE_EPS_M):
    """Merge consecutive waypoints at (nearly) the same position into one
    entry with the summed hold_duration. The 7B copies its few-shot example,
    which encodes a pause as a DUPLICATE waypoint with hold_duration (live
    2026-09-05: 'left wing, pause 2s, right wing' compiled to
    FIRST(2,2.5), SECOND(2,2.5)[2s], THIRD(2,-2.5)). Labels renumbered so
    the executor's lookup table stays sequential."""
    merged = []
    for w in wps:
        if merged and abs(merged[-1]["x"] - w["x"]) <= eps \
                   and abs(merged[-1]["y"] - w["y"]) <= eps:
            merged[-1]["hold_duration"] += w.get("hold_duration", 0.0)
        else:
            merged.append(dict(w))
    labels = ["FIRST", "SECOND", "THIRD", "FOURTH", "FIFTH", "SIXTH",
              "SEVENTH", "EIGHTH"]
    for i, w in enumerate(merged):
        w["label"] = labels[i] if i < len(labels) else f"WP{i + 1}"
    return merged

def _load_demo_waypoints():
    """Load waypoints from shared_state/waypoints.json.

    Schema v2: {"bots": {"blue_1": {"waypoints": [...]}, ...}}.
    Legacy (top-level "waypoints") loads as DEMO_DEFAULT_BOT."""
    try:
        with open(WAYPOINTS_PATH, 'r') as f:
            data = json.load(f)
    except Exception:
        _demo_state.clear()
        return
    if isinstance(data.get("bots"), dict):
        for bot, bdata in data["bots"].items():
            st = _demo_bot_state(bot)
            st["waypoints"] = _norm_demo_waypoints(bdata.get("waypoints", []))
    else:
        st = _demo_bot_state(DEMO_DEFAULT_BOT)
        st["waypoints"] = _norm_demo_waypoints(data.get("waypoints", []))

def _write_waypoints_file():
    """Persist all bots' waypoints (read-modify-write keeps other bots' lists)."""
    bots = {bot: {"waypoints": st["waypoints"]}
            for bot, st in _demo_state.items() if st["waypoints"]}
    with open(WAYPOINTS_PATH + ".tmp", 'w') as f:
        json.dump({"bots": bots}, f, indent=2)
    os.replace(WAYPOINTS_PATH + ".tmp", WAYPOINTS_PATH)

def _demo_has_active_waypoints():
    return any(st["waypoints"] for st in _demo_state.values())

def _demo_target_for_bot(bot, bx, by):
    """Return the current target label and advance if the bot has arrived.
    On final-waypoint arrival the waypath ENDS: the bot is parked (Hold) so
    the executor stops re-issuing the last Move — otherwise any external
    displacement (drag) makes the PD walk the bot back to the old target."""
    st = _demo_bot_state(bot)
    wps = st["waypoints"]
    if not wps:
        return None
    wp = wps[st["target_idx"]]
    dist = math.hypot(bx - wp["x"], by - wp["y"])
    if dist < DEMO_ARRIVAL_DIST:
        hold = wp.get("hold_duration", 0)
        if hold > 0:
            if st["arrival_time"] == 0:
                st["arrival_time"] = time.time()
                return wp["label"]
            elif time.time() - st["arrival_time"] < hold:
                return wp["label"]
        # Advance to next WP, but don't loop past the last one
        if st["target_idx"] + 1 < len(wps):
            st["target_idx"] = st["target_idx"] + 1
            st["arrival_time"] = 0
            wp = wps[st["target_idx"]]
        elif dist < DEMO_PARK_DIST:
            # Waypath complete → park (waypath cleared; stopped_idx reset so
            # "resume" replays the waypath from the start)
            st["waypoints"] = []
            st["arrival_time"] = 0
            st["stopped_idx"] = 0
            st["fast_cmd"] = {"action": "Hold"}
            _write_hold_strategy(bot)
            print(f"🏁 [{bot}] waypath complete — parked", flush=True)
            return None
        # else: not yet close enough to park — keep closing in
    return wp["label"]

def _build_compiler_world_lines(ents, start_pos):
    """World-state summary lines for the compiler prompt (shared with probe tooling)."""
    world_lines = []
    for name in sorted(ents):
        v = ents[name]
        world_lines.append(f"  {name} at ({v['x']:.1f}, {v['y']:.1f})")
    ball = ents.get("soccer_ball", {})
    if ball:
        world_lines.append(f"  soccer_ball at ({ball.get('x', 0):.1f}, {ball.get('y', 0):.1f})")
    world_lines.append(f"  START position: ({start_pos[0]}, {start_pos[1]})")
    return world_lines

def _build_compiler_sys_prompt(world_lines, start_pos):
    """Compiler system prompt (shared with probe tooling — single source of truth)."""
    landmarks_text = "\n".join(f"  {name.upper()} at ({x}, {y})" for name, (x, y) in DEMO_LANDMARKS.items())
    return f"""You are a robot path planner. Convert the task into a list of named waypoints.

FIELD ORIENTATION (from Blue's POV, standing at own goal looking toward opponent goal):
  Left = positive Y (Y > 0). Right = negative Y (Y < 0).
  Own goal = X=-4.5. Opponent goal = X=+4.5.
  "left wing" = Y positive. "right wing" = Y negative.

LANDMARKS (named positions):
{landmarks_text}

CURRENT WORLD STATE:
{chr(10).join(world_lines)}

Output ONLY raw JSON:
{{"waypoints": [{{"label": "FIRST", "x": <float>, "y": <float>, "hold_duration": <optional float>}}, ...]}}

Rules:
- Label waypoints sequentially: FIRST, SECOND, THIRD, FOURTH, FIFTH, SIXTH, ...
- Use absolute coordinates. Field: X in [-4.5, 4.5], Y in [-3.0, 3.0].
- Use the EXACT coordinates from the LANDMARKS table above. Do not compute your own.
- Add "hold_duration" (seconds) for pause/wait commands.
- "return" or "go home" means go to the bot's START position (shown in world state below).
- "kicking distance" = 0.3m from the ball.

Example:
Task: "go to the right wing, pause 2 seconds, then return"
START position: (0.0, 0.0)
Output: {{"waypoints": [{{"label": "FIRST", "x": 2.0, "y": -2.5}}, {{"label": "SECOND", "x": 2.0, "y": -2.5, "hold_duration": 2.0}}, {{"label": "THIRD", "x": 0.0, "y": 0.0}}]}}
"""

def _compile_demo_task(bot, task_text, ents):
    """One-shot LLM call: translate NL task to a waypoint list for ONE bot.
    Returns True on success."""
    if CALIB:
        # Calib vocabulary freeze (mode merge 2026-09-08): calib is the
        # hardware-only field stack — no Ollama, no waypaths (they drive
        # sim bots). Defense in depth: _handle_task_clause rejects
        # compiler vocabulary earlier; this guard covers direct calls.
        print(f"⚠ [{bot}] '{task_text}' needs the 7B compiler — demo-mode "
              f"only (calib runs without Ollama). Calib accepts: "
              f"go to (x,y) | home | face <dir> | say yes/no | look | "
              f"forward/back | turn | stop | exec | results.", flush=True)
        return True
    st = _demo_bot_state(bot)
    start_pos = _demo_start_pos_of(bot)
    world_lines = _build_compiler_world_lines(ents, start_pos)
    sys_prompt = _build_compiler_sys_prompt(world_lines, start_pos)

    user_prompt = f"Task: {task_text}\n\nOutput the JSON waypoint list."

    payload = {
        "model": DEMO_COMPILER_MODEL,
        "prompt": user_prompt,
        "system": sys_prompt,
        "stream": False,
        "keep_alive": "30m",
        "options": {"temperature": 0.0, "num_predict": 400, "num_ctx": 4096, "stop": ["<|im_end|>"]},
    }
    if "glm" in DEMO_COMPILER_MODEL:
        payload["think"] = False

    try:
        print(f"Compiling task with {DEMO_COMPILER_MODEL}: \"{task_text[:60]}\"", flush=True)
        resp = requests.post(OLLAMA_URL, json=payload, timeout=120)
        raw = resp.json().get("response", "").strip()
        if raw.startswith("```"):
            raw = raw.split("```")[1].strip("json\n")
        data = json.loads(raw)
        wps = data.get("waypoints", data)
        if isinstance(wps, list) and len(wps) > 0:
            waypoints = _merge_duplicate_waypoints(_norm_demo_waypoints(wps))
            st["waypoints"] = waypoints
            st["target_idx"] = 0
            st["arrival_time"] = 0
            st["fast_cmd"] = None
            _write_waypoints_file()
            labels = [w["label"] for w in waypoints]
            print(f"Compiled [{bot}]: {len(waypoints)} waypoints: {labels}", flush=True)
            return True
    except Exception as e:
        print(f"Compiler failed ({e}), keeping existing waypoints", flush=True)
    return False

def _write_assignment(bot, task):
    """Merge a single bot's assignment into current_strategy.json (bypasses LLM).
    Other bots' assignments are preserved — the bridge holds per-bot targets.
    Stale LLM metadata keys are dropped (fast-path writes are not LLM calls)."""
    try:
        try:
            with open(STRATEGY_PATH, 'r') as f:
                strategy = json.load(f)
        except Exception:
            strategy = {}
        assignments = strategy.get("assignments", {})
        if not isinstance(assignments, dict):
            assignments = {}
        assignments[bot] = task
        with open(STRATEGY_PATH + ".tmp", 'w') as f:
            json.dump({"assignments": assignments}, f)
        os.replace(STRATEGY_PATH + ".tmp", STRATEGY_PATH)
    except Exception:
        pass

def _write_hold_strategy(bot=DEMO_DEFAULT_BOT):
    """Write a Hold command directly to current_strategy.json (bypasses LLM)."""
    _write_assignment(bot, {"action": "Hold"})

def _write_move_strategy(bot, x, y):
    """Write a Move command directly to current_strategy.json (bypasses LLM)."""
    _write_assignment(bot, {"action": "Move", "x": x, "y": y})

def _canon_bot(name):
    """User-facing token → relay key. blue_1→blue1, yahboom1→y1,
    k1_bot→k1. Unknown names pass through unchanged."""
    n = name.lower().strip()
    if n == 'k1_bot':
        return 'k1'
    if n in CALIB_Y_ALIASES:
        return CALIB_Y_ALIASES[n]
    if re.fullmatch(r'blue_\d+', n):
        return n.replace('_', '')
    if re.fullmatch(r'blue\d+', n):
        return n
    return n


def _canon_assignments(assignments):
    """Normalize strategy slot keys through _canon_bot — ONE convention at
    the bus boundary. The 3B executor echoes Worldstate entity names
    (blue_1/blue_2: Gazebo model names) into its output; the relays and
    every fast-path writer speak canon (blue1/y1/k1). Live 2026-09-12: the
    mismatch braked every blue bot in match mode while the LLM cycles ran
    fine (latency computed — the strategy bus carried slots the bridge
    never looked up). Unknown keys pass through unchanged."""
    return {_canon_bot(k): v for k, v in assignments.items()}


def _parse_task_bot(clause):
    """Split an optional leading bot name or scope tokens from a task clause.
    Returns (bot_or_"ALL_BOTS", remaining_text, prefixed).
    prefixed=False means no explicit bot/scope: the caller decides defaults
    (task verbs -> blue1, bare control verbs -> fleet-wide)."""
    m = DEMO_BOT_PREFIX_RE.match(clause)
    if m:
        return _canon_bot(m.group(1)), m.group(2).strip(), True
    text = clause
    stripped = False
    while True:
        m = DEMO_SCOPE_TOKEN_RE.match(text)
        if not m:
            break
        text = text[m.end():]
        stripped = True
    if stripped:
        m = DEMO_SCOPE_BOTS_RE.match(text)
        if m:
            text = text[m.end():]
        return "ALL_BOTS", text.strip(), True
    return DEMO_DEFAULT_BOT, clause, False

def _demo_stop_bot(bot):
    st = _demo_bot_state(bot)
    st["stopped_idx"] = st["target_idx"]
    st["waypoints"] = []
    st["arrival_time"] = 0
    st["fast_cmd"] = {"action": "Hold"}
    _write_hold_strategy(bot)
    print(f"⚡ STOP [{bot}]: halted at current position (was heading to waypoint {st['stopped_idx']})", flush=True)

def _demo_resume_bot(bot):
    st = _demo_bot_state(bot)
    if not st["waypoints"]:
        _load_demo_waypoints()
    if st["waypoints"]:
        st["target_idx"] = st["stopped_idx"] if st["stopped_idx"] < len(st["waypoints"]) else 0
        st["arrival_time"] = 0
        st["fast_cmd"] = None
        labels = [w["label"] for w in st["waypoints"]]
        print(f"▶ RESUME [{bot}]: continuing from waypoint {st['target_idx']} ({labels[st['target_idx']] if st['target_idx'] < len(labels) else '?'})", flush=True)
    else:
        print(f"▶ RESUME [{bot}]: no waypoints to resume", flush=True)

def _demo_restart_bot(bot):
    st = _demo_bot_state(bot)
    if not st["waypoints"]:
        _load_demo_waypoints()
    if st["waypoints"]:
        st["target_idx"] = 0
        st["arrival_time"] = 0
        st["fast_cmd"] = None
        labels = [w["label"] for w in st["waypoints"]]
        print(f"▶ RESTART [{bot}]: replaying {len(st['waypoints'])} waypoints from start: {labels}", flush=True)
    else:
        print(f"▶ RESTART [{bot}]: no waypoints to restart", flush=True)

def _demo_go_home_bot(bot):
    st = _demo_bot_state(bot)
    st["waypoints"] = []
    st["target_idx"] = 0
    st["arrival_time"] = 0
    sx, sy = _demo_start_pos_of(bot)
    st["waypoints"] = _norm_demo_waypoints(
        [{"label": "HOME", "x": sx, "y": sy}])
    st["target_idx"] = 0
    st["arrival_time"] = 0
    st["fast_cmd"] = None
    _write_waypoints_file()
    print(f"🏠 GO HOME [{bot}]: waypath to START at ({sx}, {sy})", flush=True)

def _demo_direct_move(targets, x, y):
    """Coordinate fast-path: explicit coords bypass the 7B compiler entirely
    (instant AND immune to the landmark-snap failure mode, probe F1).
    Seeds a ONE-waypoint waypath — the proven arrival/park machinery
    (0.2m park -> Hold). No bridge-side motion code, no drag_twin conflict."""
    for bot in targets:
        if bot in DEMO_HEAD_K1_ALIASES:
            bot = DEMO_FACE_DEFAULT_BOT
        st = _demo_bot_state(bot)
        st["waypoints"] = _norm_demo_waypoints(
            [{"label": "FIRST", "x": x, "y": y}])
        st["target_idx"] = 0
        st["arrival_time"] = 0
        st["fast_cmd"] = None
        _write_waypoints_file()
        print(f"⚡ [{bot}] waypath to ({x}, {y}) (auto-park; executor drives)",
              flush=True)


def _write_assignment(bot, cmd):
    """Write a single assignment to current_strategy.json. Reads existing
    assignments to preserve other bots; drops stale metadata (latency_ms,
    model_name) since this bypasses the LLM cycle."""
    data = {"assignments": {}}
    try:
        with open(STRATEGY_PATH, 'r') as f:
            existing = json.load(f).get("assignments", {})
        data["assignments"] = existing
    except Exception:
        pass
    data["assignments"][bot] = cmd
    with open(STRATEGY_PATH + ".tmp", 'w') as f:
        json.dump(data, f)
    os.replace(STRATEGY_PATH + ".tmp", STRATEGY_PATH)


def _demo_goto_cmd(bot, x, y):
    """Calibration Goto: bot drives to (x,y) using its own odom feedback
    (closed loop, bridge-side). No waypath, no 3B executor, no dynamic-prompt
    injection — the evaluator writes the destination once; the bridge's odom
    loop handles motion. k1 = K1 odom loop (2026-09-06); y1/y2 = Yahboom
    odom_raw rehearsal (2026-09-08), same pipeline. bot arrives canonical
    ('k1'/'y1'/'y2'); legacy aliases normalised."""
    bot = _canon_bot(bot)
    _write_assignment(bot, {"action": "Goto", "x": x, "y": y})
    label = "K1" if bot == "k1" else "Y"
    print(f"📍 {label} GOTO [{bot}]: drive to ({x}, {y}) via odom loop", flush=True)
    if CALIB and bot == "k1":
        global _k1_damp_hint_armed, _k1_goto_t0, _k1_goto_start
        _k1_damp_hint_armed = True  # polled in the evaluator loop
        _k1_goto_t0 = time.time()
        # capture start odom so the DAMP hint compares against the right base
        try:
            import json as _json
            _odom_path = WAYPOINTS_PATH.replace('waypoints.json', 'k1_odom.json')
            with open(_odom_path) as _f:
                _o = _json.load(_f)
            _k1_goto_start = (_o.get('x', 0.0), _o.get('y', 0.0))
        except Exception:
            _k1_goto_start = None


def _demo_set_fast_cmd(bot, cmd, note):
    """Install a fast-path command (Head/Face): clear any waypath so the
    executor cannot fight the new command, keep it alive across 3B cycles
    via fast_cmd re-injection, and write the assignment for the bridge."""
    st = _demo_bot_state(bot)
    st["waypoints"] = []
    st["target_idx"] = 0
    st["arrival_time"] = 0
    st["fast_cmd"] = dict(cmd)
    _write_assignment(bot, cmd)
    print(f"⚡ [{bot}] {note} (no compiler)", flush=True)


def _demo_head_cmd(bot, pan_deg, tilt_deg):
    """Static head pose. pan_deg + = camera LEFT, tilt_deg + = UP
    (model convention; sign conversion to servo topic happens in head_cmds)."""
    k1_path = bot in DEMO_HEAD_K1_ALIASES
    if k1_path:
        bot = DEMO_FACE_DEFAULT_BOT   # K1 has no target slot — write to mirror source
    if tilt_deg != 0.0 and not hc.TILT_ENABLED and not k1_path:
        # Yahboom S2 servo fault gate — K1 pitch (RPC 2004) is a separate
        # actuator and stays enabled. On mixed hardware (blue_1 = Yahboom#1
        # + K1 mirror) the bridge pins the servo path and keeps the K1 path.
        print("⚠ tilt skipped on Yahboom: TILT_ENABLED=False (S2 servo fault — "
              "see head_cmds.py). Pan part executes.", flush=True)
        tilt_deg = 0.0
    _demo_set_fast_cmd(bot, {"action": "Head", "pan_deg": pan_deg, "tilt_deg": tilt_deg},
                       f"look (pan {pan_deg:+.0f}°, tilt {tilt_deg:+.0f}°)")


def _demo_gesture_cmd(bot, gesture):
    """Head gesture (yes = nod/tilt, no = shake/pan). Nonce id lets the bridge
    distinguish a fresh gesture from the still-persisting finished one.
    CALIB y1 'no' (2026-09-08): oscillating vyaw CANCELS in the board yaw
    PID (even ±45°@1Hz — 0.5s reversals average to zero; live twice), so
    the shake is built as a Seq of arrival-latched relative Faces — each
    swing is the PROVEN closed-loop turn. y2 keeps the servo pan (works),
    K1 keeps the RPC head. 'yes' keeps the body bob (vx axis works)."""
    if CALIB and gesture == "no" and bot in ("y1",):
        A = math.radians(CALIB_SAYNO_SHAKE_AMP_DEG)
        steps = [{"action": "Face", "relative_angle": A}]
        for _ in range(CALIB_SAYNO_SHAKE_CYCLES):
            steps.append({"action": "Face", "relative_angle": -2 * A})
            steps.append({"action": "Face", "relative_angle": 2 * A})
        steps.append({"action": "Face", "relative_angle": -A})
        _demo_seq_cmd(bot, steps)
        print(f"🔁 [{bot}] say no: {CALIB_SAYNO_SHAKE_CYCLES} closed-loop "
              f"shake swings (±{CALIB_SAYNO_SHAKE_AMP_DEG:.0f}°, arrival-"
              f"latched each)", flush=True)
        return
    k1_path = bot in DEMO_HEAD_K1_ALIASES
    if k1_path:
        bot = DEMO_FACE_DEFAULT_BOT
    if gesture == "yes" and not hc.TILT_ENABLED and not k1_path:
        print("⚠ 'say yes' refused: tilt disabled (S2 servo fault — the nod "
              "axis crashes Y#2; see head_cmds.py). Use 'say no' (pan).", flush=True)
        return
    _demo_set_fast_cmd(bot, {"action": "Head", "gesture": gesture,
                             "cycles": hc.GESTURE_CYCLES, "id": time.time()},
                       f"say {gesture} ({hc.GESTURE_CYCLES}x, {hc.GESTURE_FREQ_HZ:.0f} Hz, "
                       f"±{hc.GESTURE_AMP_PAN_DEG:.0f}°)")


def _demo_face_cmd(bot, yaw=None, relative=None):
    """Body turn-in-place: absolute yaw or relative angle (radians).
    The nonce id lets the bridge snapshot the target yaw ONCE — re-deriving
    a relative target each tick made turns endless (live 2026-09-05)."""
    cmd = {"action": "Face", "id": time.time()}
    if yaw is not None:
        cmd["yaw"] = yaw
        note = f"Face abs yaw {yaw:+.2f} rad"
    else:
        cmd["relative_angle"] = relative
        note = f"Face rel {relative:+.2f} rad (snapshotted)"
    _demo_set_fast_cmd(bot, cmd, note)


def _handle_compound_task(clause, ents):
    """Split on comma-only (digit/chain guards). Sub-clauses containing
    instant verbs (control, look/say, face/turn) route independently.
    Move-chain sub-clauses (go/move/draw/approach/patrol) are reassembled
    with 'then' connectors so the 7B compiler sees the full sequence:
    'go to wing, pause 2s, go to wing' becomes one compile task, not two
    overwrites. Bot prefix parsed once and prepended to each sub-clause
    (otherwise 'blue_2 go to wing, pause' loses blue_2 on the second
    sub-clause → ALL_BOTS → blue_1 also moves, 2026-09-06)."""
    m = DEMO_BOT_PREFIX_RE.match(clause)
    if m:
        prefix = m.group(1)
        rest = m.group(2).strip()
    else:
        prefix = None
        rest = clause
    subs = _DEMO_COMMA_SEP_RE.split(rest)
    if len(subs) > 1:
        # Check if ALL sub-clauses are compiler vocabulary (move verbs)
        # If so, rejoin as a single chain so the 7B produces one waypath.
        move_verbs = ('go', 'goto', 'move', 'drive', 'draw', 'approach',
                       'patrol', 'trace', 'return', 'circle', 'pause', 'wait')
        all_compiler = all(
            any(s.strip().startswith(v) for v in move_verbs)
            for s in subs
        )
        if all_compiler:
            rejoined = " then ".join(s.strip() for s in subs)
            full = (prefix + " " + rejoined) if prefix else rejoined
            _handle_task_clause(full, ents)
        else:
            for c in subs:
                c = c.strip()
                if c:
                    full = (prefix + " " + c) if prefix else c
                    _handle_task_clause(full, ents)
    else:
        _handle_task_clause(clause, ents)  # no split needed — original


def _handle_task_clause(clause, ents):
    """Route one task clause to its bot(s): fast-path verbs, coordinate
    fast-path, or 7B compilation. Scope tokens (all/both/yahbooms/sim)
    address every blue bot in the world state.

    Control verbs (stop/resume/restart/go home) are FLEET-WIDE when
    unprefixed — an operator's bare "stop" must always halt the show
    (lab finding 2026-08-30: per-bot default left the vision bot moving).
    An EXPLICIT bot prefix wins (lab finding 2026-08-31: "blue_2 redo"
    replayed both bots' waypaths — the prefix must scope the verb).
    Task verbs stay per-bot (unprefixed = blue1, backward compatible)."""
    blue_bots = sorted(k for k in ents if k.startswith("blue"))
    if not blue_bots and not CALIB:
        return
    # Fleet-stop safety: control-flavored tasks must NEVER reach the compiler
    # (probe F5: "stop all bots" compiled a hallucinated goal-to-goal patrol)
    if re.match(r'^(?:stop|halt)\s+(?:all|every|bots|everyone)\b', clause):
        stop_targets = (["y1", "y2", "k1"] if CALIB else blue_bots)
        for bot in stop_targets:
            _demo_stop_bot(bot)
        return
    bot, text, prefixed = _parse_task_bot(clause)
    if CALIB:
        # Hardware identity list (relay keys). Bots absent from the relay
        # simply no-op in the bridge (no publisher, no assignment effect).
        hw_bots = ["y1", "y2", "k1"]
        if bot == "ALL_BOTS" or (text in DEMO_CONTROL_VERBS and not prefixed):
            targets = hw_bots
        elif not prefixed:
            targets = ["k1"]   # field-first default in calib
        else:
            targets = [_canon_bot(bot)]
    else:
        if bot == "ALL_BOTS" or (text in DEMO_CONTROL_VERBS and not prefixed):
            targets = blue_bots
        else:
            targets = [bot]
    if not text:
        return

    # --- CALIB: home = odom origin for hardware goto bots (2026-09-08).
    # "y1 go to home" / "y1 return" / bare "home" — the demo waypath
    # go-home is executor-driven (sim semantics, dead for hardware; live:
    # the command compiled with the 7B and drove nothing). For hardware
    # the calibration start pose IS the odom origin — instant Goto(0,0).
    if CALIB and any(b in DEMO_GOTO_BOTS for b in targets):
        if re.match(r'^(?:go\s*to\s*|goto\s*|drive\s+to\s*|go\s+)?'
                    r'(?:home|origin|start|return(?:\s+to\s+start)?)$', text):
            for b in targets:
                if b in DEMO_GOTO_BOTS:
                    _demo_goto_cmd(b, 0.0, 0.0)
            print("🏠 HOME = Goto(0,0) — calibration start pose (odom origin)",
                  flush=True)
            return

    # --- Fast-path control commands (bypass compiler, instant response) ---
    if text in DEMO_FAST_STOP:
        for b in targets:
            _demo_stop_bot(b)
        return
    if text in DEMO_FAST_RESUME:
        for b in targets:
            _demo_resume_bot(b)
        return
    if text in DEMO_FAST_RESTART:
        for b in targets:
            _demo_restart_bot(b)
        return
    if text in DEMO_FAST_HOME:
        for b in targets:
            _demo_go_home_bot(b)
        return

    # --- CALIB: Yahboom open-loop TimedMove (encoder odom unreliable — slip).
    # "y1 forward 0.5" / "y1 back 0.3" / "y1 turn 90" (+ = CCW). Sequential
    # for fleets: yahbooms drive one at a time (first target in list first).
    if CALIB:
        m = re.match(r'^(forward|back|backward)s?\s+(\d+(?:\.\d+)?)$', text)
        if m:
            dist = float(m.group(2))
            vx = Y_CALIB_VX * (1.0 if m.group(1).startswith('for') else -1.0)
            for b in targets:
                if b in ("y1", "y2"):
                    dur = dist / Y_CALIB_VX
                    _write_assignment(b, {"action": "TimedMove", "vx": vx,
                                          "vyaw": 0.0, "duration_s": round(dur, 3),
                                          "id": time.time()})
                    print(f"⏱ TIMED [{b}]: {m.group(1)} {dist}m @ {abs(vx)}m/s, "
                          f"{dur:.2f}s (open-loop)", flush=True)
                elif b == "k1":
                    print("⚠ k1 has closed-loop Goto — use 'k1 go to (x,y)'", flush=True)
            return
        m = re.match(r'^turn\s+(-?\d+(?:\.\d+)?)\s*(?:deg(?:rees)?|[o°])?$', text)
        if m:
            # CLOSED-LOOP turn (2026-09-08): routes to the relative-Face
            # machinery (estimator-yaw feedback, P-control, arrival latch,
            # spin caps) — NOT open-loop timing. Live evidence: the board's
            # actual yaw authority is ~0.27 rad/s vs the 0.5 commanded
            # (turn 45 -> +23.5°) and sub-0.5s commands are swallowed by
            # motor spin-up (turn 10/15 -> nothing). Odom YAW tracks the
            # physical body (gyro-fused) unlike wheel-distance — closing
            # the loop on it is legitimate and fixes both problems.
            # SIGN (user 2026-09-08, "counter intuitive"): positive =
            # CLOCKWISE/right — the boot-compass convention (nose north,
            # turn 90 -> nose east). ROS yaw is CCW-positive, hence the
            # negation.
            deg = float(m.group(1))
            for b in targets:
                _demo_face_cmd(b, relative=-math.radians(deg))
            print(f"🔁 TURN: {deg:+.0f}° closed-loop on odom yaw "
                  f"(+ = clockwise/right, arrival-latched; slow-authority "
                  f"bots just take longer)", flush=True)
            return

    # --- Calibration Goto (closed-loop odom, no digital twin) ---
    # "k1 go to (1,0)" and "y1 go to (0.5,0)" route to the odom-loop action
    # (bridge drives on the bot's OWN odometry); "blue1 go to (1,0)" goes to
    # the sim-pose Move. Mixed prefix routes each correctly. Yahboom = K1
    # field-test rehearsal (2026-09-08): same pipeline, coarse arrival.
    if any(b in DEMO_GOTO_BOTS for b in targets):
        m = DEMO_COORD_RE.match(text)
        if m:
            for b in targets:
                if b in DEMO_GOTO_BOTS:
                    _demo_goto_cmd(b, float(m.group(1)), float(m.group(2)))
                else:
                    _demo_direct_move([b], float(m.group(1)), float(m.group(2)))
            return

    # --- Coordinate fast-path (explicit coords, no LLM): seed a ONE-waypoint
    # waypath — the PROVEN machinery (evaluator arrival + park at 0.2m ->
    # Hold; drag_twin's waypath-watch sees the 3B's plain Move targets).
    # The round-5 Seq/latch experiment here caused the drag_twin teleport
    # loop — reverted 2026-09-05. ---
    m = DEMO_COORD_RE.match(text)
    if m:
        _demo_direct_move(targets, float(m.group(1)), float(m.group(2)))
        return

    # --- Sequence chains: "<step>, then <step>..." Decision table (5d):
    #   all instant steps (face/turn/rotate/look/say/pause) -> Seq (bridge)
    #   all move/pause steps (goto coords)                     -> WAYPATH
    #     (proven machinery; drag_twin sees the 3B's plain Move targets —
    #      chained Seq-moves caused the teleport loop, rewound 5c)
    #   instant + move mixed                                    -> rejected
    #   anything else (compile vocabulary)                      -> 7B below
    segments = DEMO_CHAIN_SPLIT_RE.split(text)
    if len(segments) > 1:
        steps = [_chain_step(s) for s in segments]
        move_segs = [_chain_move_segment(s) for s in segments]
        has_instant = any(s is not None and s.get('action') != 'Pause'
                          for s in steps)
        has_move = any(ms is not None and ms['kind'] == 'move'
                       for ms in move_segs)
        if all(s is not None for s in steps) and (has_instant or not has_move):
            if bot == "ALL_BOTS":
                # Explicit "all" scope overrides the one-bot-per-chain rule
                # (user 2026-09-06): every blue bot runs the same sequence.
                for b in targets:
                    _demo_seq_cmd(b, steps)
                return
            seq_bot = bot if prefixed else DEMO_FACE_DEFAULT_BOT
            if seq_bot in DEMO_HEAD_K1_ALIASES:
                seq_bot = DEMO_FACE_DEFAULT_BOT   # K1 has no target slot
            _demo_seq_cmd(seq_bot, steps)
            return
        if all(ms is not None for ms in move_segs) and has_move:
            wp_targets = [DEMO_FACE_DEFAULT_BOT if b in DEMO_HEAD_K1_ALIASES
                          else b for b in targets]
            for b in wp_targets:
                _demo_waypath_chain(b, move_segs, ents)
            return
        if has_instant and has_move:
            print(f"⚠ \"{clause}\" mixes facing and move steps.", flush=True)
            print("   Chains are either moves+pauses OR facing/head steps — "
                  'split them: e.g. "face west" first, then "go to (1,1)".',
                  flush=True)
            return
        # compile vocabulary present -> the 7B owns the compound (below)

    # --- Head fast-path (look/say): default blue_1 (body bot — bare 'say'
    # triggers the bridge body-gesture fork). Camera work = 'blue_2 ...'.
    # k1/k1_bot prefix reroutes inside _demo_head_cmd/_demo_gesture_cmd. ---
    if text in DEMO_HEAD_LOOK:
        pan, tilt = DEMO_HEAD_LOOK[text]
        head_targets = [DEMO_HEAD_DEFAULT_BOT] if not prefixed else targets
        for b in head_targets:
            _demo_head_cmd(b, pan, tilt)
        return
    if text in DEMO_HEAD_GESTURES:
        head_targets = [DEMO_HEAD_DEFAULT_BOT] if not prefixed else targets
        for b in head_targets:
            _demo_gesture_cmd(b, DEMO_HEAD_GESTURES[text])
        return

    # --- Face fast-path (body turn-in-place): default blue_1 ---
    # CALIB uses the boot compass (yaw 0 = north — the power-cycle ritual);
    # demo keeps the world frame (sim twins spawn facing east/+X).
    face_map = DEMO_FACE_ABS_CALIB if CALIB else DEMO_FACE_ABS
    face_targets = [DEMO_FACE_DEFAULT_BOT] if not prefixed else [
        DEMO_FACE_DEFAULT_BOT if b in DEMO_HEAD_K1_ALIASES else b for b in targets]
    if text in face_map:
        for b in face_targets:
            _demo_face_cmd(b, yaw=face_map[text])
        return
    if text in DEMO_TURN_REL:
        for b in face_targets:
            _demo_face_cmd(b, relative=DEMO_TURN_REL[text])
        return
    m = DEMO_ROTATE_RE.match(text)
    if m:
        for b in face_targets:
            _demo_face_cmd(b, relative=math.radians(float(m.group(1))))
        return

    # --- Facing/instant words must not reach the 7B: it has no facing
    # concept and would guess coordinates for them (the original
    # "face west, then go to 1,1" garbage compile). Landmark/shape
    # compounds WITHOUT these words compile normally. ---
    if DEMO_INSTANT_WORD_RE.search(text):
        print(f"⚠ \"{clause}\" mixes compile and facing/head commands.", flush=True)
        print("   Split them: run the compiler task (landmark/shape) and the "
              'facing/head command ("face west", "say no", ...) separately.',
              flush=True)
        return

    # --- Heading-relative guard: "forward/backward N m" has no yaw ground
    # truth (v7 Task 3a) — the compiler would guess garbage coordinates ---
    if DEMO_HEADING_REL_RE.search(text):
        print(f"⚠ \"{text}\" is heading-relative (forward/backward) — bots have no "
              f"yaw in the world model yet, so the compiler would guess. "
              f"Use coordinates instead: e.g. \"go to (2, 0)\" or a landmark.", flush=True)
        return

    # --- Verb guard: scope-only clauses must not reach the compiler ---
    if not DEMO_TASK_VERB_RE.search(text):
        print(f"⚠ no actionable verb in \"{clause}\" — ignored", flush=True)
        return

    # --- CALIB vocabulary freeze (cleanup 2026-09-08): everything that
    # falls through to here is compiler vocabulary (landmarks/shapes/
    # patrols/ball/via-points) — demo-mode features that drive sim bots.
    # In calib they compiled dead waypaths ("y1 go to home" once compiled
    # with the 7B and drove nothing). Reject loudly with the accepted list.
    if CALIB:
        print(f"⚠ \"{clause}\" is demo-mode (compiler) vocabulary — calib is "
              f"a hardware-only field stack.", flush=True)
        print("   Calib accepts: yN/k1 go to (x,y) | go to home | return | "
              "face <dir> | say yes/no | look <dir> | stop |", flush=True)
        print("   yN forward/back <m> | yN turn <deg> | exec <runbook> | "
              "results. Chains/landmarks/shapes = demo mode.", flush=True)
        return

    # --- Normal path: compile task via 7B LLM (per bot) ---
    for b in targets:
        _compile_demo_task(b, text, ents)

def _check_task_input(ents, match_state):
    """Check if task_input.json changed; if so, recompile or execute control command.
    Clauses are split on ';' and routed per bot (A2bot: bot prefix / scope)."""
    global _last_task_mtime
    if not os.path.exists(TASK_INPUT_PATH):
        return
    try:
        mtime = os.path.getmtime(TASK_INPUT_PATH)
        if mtime == _last_task_mtime:
            return
        _last_task_mtime = mtime
        with open(TASK_INPUT_PATH, 'r') as f:
            data = json.load(f)
        task_text = data.get("task", "").strip().lower().strip('"').strip("'")
        if not task_text:
            return
        for clause in task_text.split(';'):
            clause = clause.strip()
            if clause:
                _handle_compound_task(clause, ents)
    except Exception:
        pass

def _persist_non_llm_assignments(data):
    """Carry forward assignments that the 3B executor never touches
    (e.g. k1_bot Goto) — otherwise they get stripped on every cycle
    because k1_bot is removed from min_ents (phantom-assignment rule)."""
    try:
        with open(STRATEGY_PATH, 'r') as f:
            existing = json.load(f).get("assignments", {})
        assignments = data.setdefault("assignments", {})
        for bname, cmd in existing.items():
            if bname not in assignments and cmd.get("action") == "Goto":
                assignments[bname] = cmd
    except Exception:
        pass


def _demo_reinject_fast_cmds(data):
    """Fast-path authority: a bot with a fast_cmd (Hold from park/stop/go-home,
    Head gesture/pose, Face) is controlled EXCLUSIVELY by that command.
    The fast_cmd OVERRIDES whatever the executor said for it — the 3B
    hallucinated assignments for invisible/phantom bots (e.g. 'blue_3 Move
    to ball', trace 2026-09-05), and gap-filling only was not enough.
    A new compile/task clears fast_cmd, handing control back to the LLM."""
    assignments = data.setdefault("assignments", {})
    for bname, st in _demo_state.items():
        fc = st.get("fast_cmd")
        if fc:
            assignments[bname] = dict(fc)
    return data


def _demo_inject_targets(min_ents, ents):
    """Demo executor payload: per-bot target labels + flat waypoint table.

    Contract (trace-verified 2026-08-30): the 3B assigns EVERY bot it can see
    unless constrained — so non-targeted blue bots are STRIPPED from the
    snapshot and only listed bots may appear in assignments. Labels are
    prefixed per bot (B1_FIRST, B2_FIRST) when multiple bots are active so
    the lookup stays flat; a single active bot keeps its raw labels."""
    active = []
    for bname in sorted(k for k in ents if k.startswith("blue")):
        bv = ents[bname]
        st = _demo_bot_state(bname)
        if st["start_pos"] is None:
            st["start_pos"] = (bv["x"], bv["y"])
        target_label = _demo_target_for_bot(bname, bv["x"], bv["y"])
        if target_label:
            active.append((bname, target_label, st["waypoints"]))
    if not active:
        # No active waypath anywhere: strip ALL blue bots. Unstripped, the
        # 3B hallucinates soccer assignments that override Hold/Head/Face
        # fast_cmds the moment the last bot parks (post-park zombie drives:
        # both bots drove to the ball / own goal — trace-proven 2026-09-05,
        # raw_response: roles + phantom blue_3 + "Move to ball"). Parked and
        # fast-path-controlled bots are driven ONLY by fast_cmd re-injection
        # and must stay invisible to the executor.
        for bname in [k for k in min_ents if k.startswith("blue")]:
            del min_ents[bname]
        return
    single = len(active) == 1
    prefixes = {b: ("" if single else f"B{i + 1}_")
                for i, (b, _, _) in enumerate(active)}
    min_ents["targets"] = {b: f"{prefixes[b]}{label}" for b, label, _ in active}
    wp_table = {}
    for b, _, wps in active:
        for w in wps:
            wp_table[f"{prefixes[b]}{w['label']}"] = {"x": w["x"], "y": w["y"]}
    min_ents["waypoints"] = wp_table
    # Strip bots without a target — the executor must never assign them
    for bname in [k for k in min_ents if k.startswith("blue")]:
        if bname not in min_ents["targets"]:
            del min_ents[bname]

def _build_text_world(ents, match_state, velocities=None):
    """Condensed text transform of the world snapshot in dictionary vocabulary.
    Ball first, then blue bots, then red bots; score and status appended.
    ~250 tok cap (~40 tokens for a 7-line 3vs3 world)."""
    lines = []
    if "soccer_ball" in ents:
        b = ents["soccer_ball"]
        lines.append(f"soccer_ball at ({b['x']:.1f}, {b['y']:.1f})")
    for name in sorted(k for k in ents if k.startswith("blue")):
        v = ents[name]
        base = f"{name} at ({v['x']:.1f}, {v['y']:.1f})"
        if velocities and name in velocities:
            vx, vy = velocities[name]
            if math.hypot(vx, vy) >= 0.3:
                base += f" moving ({vx:.1f}, {vy:.1f})"
        lines.append(base)
    for name in sorted(k for k in ents if k.startswith("red")):
        v = ents[name]
        base = f"{name} at ({v['x']:.1f}, {v['y']:.1f})"
        if velocities and name in velocities:
            vx, vy = velocities[name]
            if math.hypot(vx, vy) >= 0.3:
                base += f" moving ({vx:.1f}, {vy:.1f})"
        lines.append(base)
    ms = match_state or {}
    lines.append(f"score blue {ms.get('blue', 0)} : {ms.get('red', 0)} red")
    lines.append(f"status {ms.get('status', 'playing')}")
    return "\n".join(lines)

def _world_text_from_dict(data):
    """Render a sample INPUT JSON dict as text world lines (text-mode samples)."""
    lines = []
    if "soccer_ball" in data:
        b = data["soccer_ball"]
        lines.append(f"soccer_ball at ({b['x']:.1f}, {b['y']:.1f})")
    for name in sorted(data):
        if name == "soccer_ball" or not isinstance(data[name], dict):
            continue
        v = data[name]
        if "x" not in v or "y" not in v:
            continue
        lines.append(f"{name} at ({v['x']:.1f}, {v['y']:.1f})")
    return "\n".join(lines)

def _text_from_assignments(assignments, explain_active, analysis_val, oracle_val):
    """Render sample ASSISTANT assignments as text output lines."""
    out = []
    if explain_active:
        out.append(f"ANALYSIS: {analysis_val}")
        out.append(f"ORACLE: {oracle_val}")
    for bot in sorted(assignments):
        a = assignments[bot]
        action = a.get("action", "Move")
        if str(action).lower() == "kick":
            tx = a.get("target_x")
            ty = a.get("target_y")
            if tx is not None and ty is not None:
                out.append(f"{bot} pass to ({tx}, {ty})")
            elif a.get("role", "") == "goalie":
                out.append(f"{bot} clear the ball")
            else:
                out.append(f"{bot} kick")
        elif a.get("role", "") == "goalie":
            out.append(f"{bot} cover the goal line at ({a['x']}, {a['y']})")
        else:
            out.append(f"{bot} move to ({a['x']}, {a['y']})")
    return "\n".join(out)

def _extract_json_block(content, start_pos):
    """Brace-match a JSON object starting at start_pos. Returns (json_str, end_idx)."""
    brace_count = 0
    json_start = -1
    for idx in range(start_pos, len(content)):
        char = content[idx]
        if char == '{':
            if brace_count == 0:
                json_start = idx
            brace_count += 1
        elif char == '}':
            brace_count -= 1
            if brace_count == 0:
                return content[json_start:idx + 1], idx + 1
    return None, -1

def _clean_text_samples(content, explain_active):
    """Convert sample JSON blocks to text format (Phase I text mode).
    INPUT JSON -> world lines; ASSISTANT JSON -> bot lines
    (ANALYSIS:/ORACLE: prefixes in explain mode)."""
    output = ""
    last_idx = 0
    for m in re.finditer(r'INPUT:\s*', content):
        output += content[last_idx:m.start()]
        input_json, after_input = _extract_json_block(content, m.end())
        if input_json is None:
            output += content[last_idx:]
            return output
        a_match = re.search(r'(?:ASSISTANT|OUTPUT):\s*', content[after_input:])
        if not a_match:
            output += content[last_idx:]
            return output
        assistant_pos = after_input + a_match.end()
        output += content[after_input:after_input + a_match.start()] + "INPUT:\n"
        try:
            in_data = json.loads(input_json)
            world_text = _world_text_from_dict(in_data)
        except Exception:
            world_text = ""
        output += world_text + "\n"
        assist_json, after_assist = _extract_json_block(content, assistant_pos)
        if assist_json is None:
            output += content[last_idx:]
            return output
        try:
            data = json.loads(assist_json)
        except Exception:
            try:
                data = json.loads(re.sub(r'\n\s*', ' ', assist_json))
            except Exception:
                data = {}
        analysis_val = data.get("analysis", "Tactical assessment of entity positions and ball trajectory.")
        oracle_val = data.get("oracle", "Predictive optimization of team response to secure match advantage.")
        assignments = data.get("assignments", data)
        assignments.pop("analysis", None)
        assignments.pop("oracle", None)
        output += "ASSISTANT:\n" + _text_from_assignments(assignments, explain_active, analysis_val, oracle_val) + "\n"
        last_idx = after_assist
    output += content[last_idx:]
    return output

def _determine_mode():
    """Read mode from active_scenario.json (written by setup_r2k.py at boot).
    Falls back to '3vs3' if unavailable."""
    try:
        with open(SCENARIO_PATH, 'r') as f:
            data = json.load(f)
        scenario_name = data.get("scenario", data.get("scenario_name", ""))
        mode = data.get("mode") or (scenario_name.split('_')[0] if '_' in scenario_name else "3vs3")
        return mode
    except Exception:
        return "3vs3"

def _read_fragment(name):
    """Read a fragment file, return empty string if missing."""
    path = os.path.join(FRAGMENTS_DIR, name)
    try:
        with open(path, 'r') as f:
            return f.read()
        # Strip trailing newline to avoid double-newlines when concatenating
    except FileNotFoundError:
        return ""


def _clean_json_samples(content, explain_active):
    """Transform sample ASSISTANT blocks: inject or strip analysis/oracle keys.
    Duplicated from setup_r2k.py — needed at runtime because the evaluator
    assembles prompts from fragments directly (Phase 2.5b), bypassing
    setup_r2k.py's boot-time transformation. Without this, --explain mode
    has no string examples for analysis/oracle, and Qwen 3B fills oracle
    with JSON strategy data instead of text.
    """
    pattern = r'(?:ASSISTANT|OUTPUT):\s*'
    matches = list(re.finditer(pattern, content))
    if not matches:
        return content
    output = ""
    last_idx = 0
    for m in matches:
        start_pos = m.start()
        end_pos = m.end()
        output += content[last_idx:start_pos]
        brace_count = 0
        json_start = -1
        json_end = -1
        for idx in range(end_pos, len(content)):
            char = content[idx]
            if char == '{':
                if brace_count == 0:
                    json_start = idx
                brace_count += 1
            elif char == '}':
                brace_count -= 1
                if brace_count == 0:
                    json_end = idx + 1
                    break
        if json_start == -1 or json_end == -1:
            output += content[start_pos:end_pos]
            last_idx = end_pos
            continue
        raw_json = content[json_start:json_end]
        before_text = content[max(0, start_pos - 300):start_pos]
        analysis_val = "Tactical assessment of entity positions and ball trajectory."
        oracle_val = "Predictive optimization of team response to secure match advantage."
        if "DEFENSIVE PASS" in before_text or "CLEARANCE" in before_text:
            analysis_val = "blue_1 clears the ball from the defensive zone towards blue_2."
            oracle_val = "Passing the ball out of danger into the midfield."
        elif "ANTI-CLUSTERING" in before_text:
            analysis_val = "blue_1 attacks the ball while blue_2 drops back to support and avoid clustering."
            oracle_val = "Maintain optimal distance between teammates to control the field."
        elif "BOUNDARY STAGING" in before_text:
            analysis_val = "blue_1 moves to intercept the ball near the boundary while blue_2 guards the goal."
            oracle_val = "Secure the defensive line to prevent any immediate shots on goal."
        try:
            data = json.loads(raw_json)
        except Exception:
            try:
                sanitized = re.sub(r'\n\s*', ' ', raw_json)
                data = json.loads(sanitized)
            except Exception:
                data = {}

        if explain_active:
            new_data = {}
            new_data["analysis"] = data.get("analysis", analysis_val)
            new_data["oracle"] = data.get("oracle", oracle_val)
            if "assignments" in data:
                new_data["assignments"] = data["assignments"]
            else:
                data.pop("analysis", None)
                data.pop("oracle", None)
                new_data["assignments"] = data
            formatted_json = json.dumps(new_data, separators=(',', ': '))
        else:
            if "assignments" in data:
                new_data = {"assignments": data["assignments"]}
            else:
                data.pop("analysis", None)
                data.pop("oracle", None)
                new_data = {"assignments": data}
            formatted_json = json.dumps(new_data, separators=(',', ': '))
        output += "ASSISTANT: " + formatted_json
        last_idx = json_end
    output += content[last_idx:]
    return output

def _assemble_prompt(status, mode, n_blue=3):
    """Assemble system prompt from fragments based on (status, mode).
    Fragment load order (matches setup_r2k.py / dump_prompt.py):
      1. header.txt (static, contains {{EXPLAIN_INSTRUCTION}} placeholder)
      2. rules_core.txt (static)
      3. rules_<status>.txt (game-phase; falls back to rules_<mode>.txt)
      4. rules_<mode>.txt (mode rules — always loaded; rules_<status> is ADDITIVE)
      5. samples_<status>.txt (game-phase; falls back to samples_<mode>.txt)
      6. samples_<mode>.txt (mode samples — always loaded; samples_<status> is ADDITIVE)

    Note: game-phase fragments are ADDITIVE to mode fragments, not replacements.
    The mode fragments (rules_3vs3.txt, samples_3vs3.txt) define the base behavior;
    game-phase fragments add status-specific instructions on top.
    Fallback: if rules_<status>.txt doesn't exist → skip it (mode rules suffice).
    """
    is_explain = os.getenv("R2K_EXPLAIN", "0") == "1"
    text_header = _text_output_header(n_blue)
    if TEXT_MODE:
        explain_instr = TEXT_EXPLAIN_INSTRUCTION if is_explain else text_header
        output_format = "OUTPUT FORMAT: " + (TEXT_EXPLAIN_INSTRUCTION if is_explain else text_header)
    else:
        explain_instr = (
            "- Include 'analysis', 'oracle', and 'assignments' keys."
            if is_explain
            else "- Output ONLY the 'assignments' key."
        )
        output_format = "Output ONLY pure, raw JSON."
    parts = []
    # Static fragments
    header = _read_fragment("header.txt")
    header = header.replace("Output ONLY pure, raw JSON.", output_format)
    header = header.replace("{{EXPLAIN_INSTRUCTION}}", explain_instr)
    parts.append(header)
    if TEXT_MODE:
        parts.append(_read_fragment("rules_core_text.txt") or _read_fragment("rules_core.txt"))
    else:
        if mode == "demo":
            parts.append(_read_fragment("rules_demo_core.txt") or _read_fragment("rules_core.txt"))
        else:
            parts.append(_read_fragment("rules_core.txt"))
    # Game-phase rules (additive — falls back to nothing if missing)
    if status != "playing":
        phase_rules = _read_fragment(f"rules_{status}.txt")
        if phase_rules:
            parts.append(phase_rules)
    # Mode rules (always loaded)
    parts.append(_read_fragment(f"rules_{mode}.txt"))
    # Game-phase samples (additive — falls back to nothing if missing)
    if status != "playing":
        phase_samples = _read_fragment(f"samples_{status}.txt")
        if phase_samples:
            parts.append(_clean_text_samples(phase_samples, is_explain) if TEXT_MODE else _clean_json_samples(phase_samples, is_explain))
    # Mode samples (always loaded)
    mode_samples = _read_fragment(f"samples_{mode}.txt")
    if mode_samples:
        parts.append(_clean_text_samples(mode_samples, is_explain) if TEXT_MODE else _clean_json_samples(mode_samples, is_explain))
    # Join with double-newlines between fragments, strip trailing whitespace
    return "\n\n".join(p for p in parts if p.strip()).strip()

def _get_sys_prompt(status):
    """Return the assembled system prompt for the current (status, mode).
    Caches by (status, mode) tuple — re-reads fragment files only on status change."""
    global _active_mode, _active_n_blue
    if _active_mode is None:
        _active_mode = _determine_mode()
        _active_n_blue = _n_blue_from_mode(_active_mode)
    key = (status, _active_mode)
    if key not in _prompt_cache:
        _prompt_cache[key] = _assemble_prompt(status, _active_mode, _active_n_blue)
    return _prompt_cache[key]

def log_llm_call(world_snapshot, sys_prompt, raw_response, parse_code, latency_ms, tokens_limit, is_explain, timings=None):
    try:
        prompt_hash = hashlib.sha1(sys_prompt.encode()).hexdigest()[:16]
        record = {
            "t": time.time(),
            "world_snapshot": world_snapshot,
            "sys_prompt_hash": prompt_hash,
            "raw_response": raw_response[:2000] if raw_response else "",
            "parse_code": parse_code,
            "latency_ms": latency_ms,
            "model": MODEL_NAME,
            "num_predict": tokens_limit,
            "explain": is_explain,
        }
        # Ollama cache/timing metrics (from /api/generate response, ns → ms).
        # prompt_eval_count drops on prefix-cache hits (system prompt reused);
        # prompt_eval_duration vs eval_duration splits prefill vs generation.
        if timings:
            record["prompt_eval_count"] = timings.get("prompt_eval_count")
            record["eval_count"] = timings.get("eval_count")
            record["prompt_eval_duration_ms"] = round(timings.get("prompt_eval_duration", 0) / 1e6, 1)
            record["eval_duration_ms"] = round(timings.get("eval_duration", 0) / 1e6, 1)
            record["load_duration_ms"] = round(timings.get("load_duration", 0) / 1e6, 1)
            record["total_duration_ms"] = round(timings.get("total_duration", 0) / 1e6, 1)
        with open(LLM_TRACE_PATH, 'a') as f:
            f.write(json.dumps(record) + "\n")
    except Exception:
        pass

def fast_parse(text):
    start = text.find('{')
    end = text.rfind('}')
    if start == -1 or end == -1: return None, 0
    json_str = text[start:end+1]
    
    try: return json.loads(json_str), 0
    except json.JSONDecodeError: pass 
        
    json_str = re.sub(r',\s*\}', '}', json_str)
    json_str = re.sub(r',\s*\]', ']', json_str)
    json_str = re.sub(r'"y:', '"y":', json_str)  # fix missing closing quote on y key (compact JSON artifact)
    try: return json.loads(json_str), 1
    except json.JSONDecodeError:
        assignments_match = re.search(r'"assignments"\s*:\s*(\{.*?\})\s*\}', json_str, re.DOTALL)
        if assignments_match:
            fallback = '{"analysis": "⚡ Fallback aktiv.", "assignments": ' + assignments_match.group(1) + '}'
            try: return json.loads(fallback), 2
            except: pass
    return None, 3

TEXT_LINE_RE = re.compile(
    r'^\s*blue_(\d+)\s+(?:move to \((-?[\d.]+),\s*(-?[\d.]+)\)|'
    r'cover the goal line at \((-?[\d.]+),\s*(-?[\d.]+)\)|(kick)|(hold position)|'
    r'pass to \((-?[\d.]+),\s*(-?[\d.]+)\)|(clear the ball))\s*$'
)

def text_parse(text):
    """Parse condensed text output (Phase I text mode): one line per bot.
    Accepts: 'blue_1 move to (2.2, 0.3)', 'blue_1 cover the goal line at
    (-4.0, 1.5)', 'blue_1 kick', 'blue_1 pass to (3.0, -1.0)',
    'blue_1 clear the ball', 'blue_1 hold position'. Ignores
    ANALYSIS:/ORACLE:/prose lines.
    Returns (assignments_dict, code); code 0 = all lines parsed,
    1 = partial (some lines unparseable), None if no bot line found
    (caller falls back to fast_parse)."""
    assignments = {}
    partial = False
    for line in text.splitlines():
        line = line.strip()
        if not line:
            continue
        m = TEXT_LINE_RE.match(line)
        if not m:
            if line.startswith("blue_"):
                partial = True
            continue
        bot = f"blue_{int(m.group(1))}"
        if m.group(6):  # kick
            assignments[bot] = {"role": "attacker", "action": "Kick"}
        elif m.group(7):  # hold position
            assignments[bot] = {"role": "defender", "action": "Hold"}
        elif m.group(8):  # pass to (x, y) -> Kick with target_x/target_y
            assignments[bot] = {
                "role": "attacker",
                "action": "Kick",
                "target_x": float(m.group(8)),
                "target_y": float(m.group(9)),
            }
        elif m.group(10):  # clear the ball -> goalie Kick
            assignments[bot] = {"role": "goalie", "action": "Kick"}
        elif m.group(4):  # cover the goal line at (x, y) -> role goalie
            assignments[bot] = {
                "role": "goalie",
                "action": "Move",
                "x": float(m.group(4)),
                "y": float(m.group(5)),
            }
        else:  # move to (x, y)
            assignments[bot] = {
                "role": "attacker",
                "action": "Move",
                "x": float(m.group(2)),
                "y": float(m.group(3)),
            }
    if not assignments:
        return None, 2
    return {"assignments": assignments}, 1 if partial else 0

def main():
    print(f"--- R2K Evaluator (Native Edition) ---", flush=True)
    print(f"Trace log: {LLM_TRACE_PATH}", flush=True)

    # Demo mode: quiescent boot — waypoints.json is NOT auto-loaded (with two
    # hardware bots an auto-started waypath is a lab hazard). The waypath is
    # lazy-loaded on the first "resume"/"restart"/task; bots stand until then.
    _demo_state.clear()

    last_mtime = 0
    last_ents_hash = 0
    prev_ents = {}  # position history for velocity computation
    prev_ents_time = 0.0  # timestamp of last prev_ents update
    
    while True:
        try:
            if CALIB:
                # CALIB = routing-only field stack (mode merge 2026-09-08):
                # no 3B executor cycles, no Worldstate dependency, one
                # writer per command. The executor/waypath machinery is
                # demo-mode vocabulary (it clobbered strategy slots with
                # blue_1 Move assignments while the user drove hardware —
                # the "assignment landed but a ghost rewrote it" class).
                # _check_task_input self-gates on mtime (instant when
                # unchanged); _calib_damp_hint_tick is file-based.
                _check_task_input({}, {})
                _calib_damp_hint_tick()
                time.sleep(0.02); continue
            if not os.path.exists(WORLD_STATE_PATH):
                time.sleep(0.1); continue
                
            mtime = os.path.getmtime(WORLD_STATE_PATH)
            if mtime == last_mtime:
                time.sleep(0.02); continue
                
            try:
                with open(WORLD_STATE_PATH, 'r') as f: world_data = json.load(f)
            except Exception:
                time.sleep(0.05); continue
            
            ents = world_data.get("entities", {})
            if not any("blue" in k for k in ents.keys()):
                last_mtime = mtime; continue

            match_state = world_data.get("match_state", {})
            status = match_state.get("status", "playing")

            # Demo mode: check for new task input (interactive re-compilation)
            if _active_mode == "demo" or CALIB:
                _check_task_input(ents, match_state)
                _calib_damp_hint_tick()
                # If no bot has waypoints, skip LLM call — the fast-path
                # control command already wrote current_strategy.json directly
                if not _demo_has_active_waypoints():
                    last_mtime = mtime
                    continue

            # Skip LLM call if entity positions AND status haven't changed
            # (aggregator writes at 10Hz unconditionally — 64% of writes have
            # identical positions). temperature: 0.0 makes the LLM deterministic,
            # so identical input → identical output → wasted GPU time + repetitive
            # visualizer output. Including status in the hash prevents missing
            # status transitions (e.g. ball_out while bots hold still).
            # Phase I: hash the TRANSFORMED text (or JSON) — the exact payload.
            if TEXT_MODE:
                hash_src = _build_text_world(ents, match_state)
            else:
                hash_src = json.dumps({"ents": ents, "status": status}, sort_keys=True)
            ents_hash = hash(hash_src)
            if ents_hash == last_ents_hash and _active_mode != "demo":
                last_mtime = mtime; continue
            last_ents_hash = ents_hash

            # Future world model — project all entities to t + horizon.
            # Ball: exponential velocity decay (k=1.26, empirically measured).
            # Bots: linear motion capped at max speed (bridge PD controller).
            # Blue bot prediction is valid: at t+horizon they're still executing
            # the PREVIOUS command, not the one being generated now.
            PREDICT_HORIZON_S = 0.746  # hardwired; future: dynamic from measured latency
            if _active_mode == "demo":
                PREDICT_HORIZON_S = 0  # no prediction — demo uses position-based sequence, not time
            BALL_DECAY_K = 1.26
            BOT_MAX_SPEED = 0.8

            velocities = {}
            now_t = time.time()
            dt = now_t - prev_ents_time if prev_ents_time > 0 else 0.1
            prev_ents_time = now_t
            if dt < 0.01:
                dt = 0.1
            for k, v in ents.items():
                if k in prev_ents:
                    pv = prev_ents[k]
                    velocities[k] = ((v["x"] - pv["x"]) / dt, (v["y"] - pv["y"]) / dt)

            prev_ents = {k: {"x": v["x"], "y": v["y"]} for k, v in ents.items()}

            for k, v in ents.items():
                if k not in velocities:
                    continue
                vx, vy = velocities[k]
                speed = math.hypot(vx, vy)
                if speed < 0.3:
                    continue
                if k == "soccer_ball":
                    dist = (speed / BALL_DECAY_K) * (1 - math.exp(-BALL_DECAY_K * PREDICT_HORIZON_S))
                else:
                    dist = min(speed * PREDICT_HORIZON_S, BOT_MAX_SPEED * PREDICT_HORIZON_S)
                v["x"] = v["x"] + (vx / speed) * dist
                v["y"] = v["y"] + (vy / speed) * dist

            # Phase 2.5b: Dynamic prompt injection — assemble prompt from fragments
            # based on match_state.status. Cached by (status, mode) tuple.
            sys_prompt = _get_sys_prompt(status)

            is_explain = os.getenv("R2K_EXPLAIN", "0") == "1"

            # Phase I: text transform (dictionary vocabulary) or JSON min_ents.
            if TEXT_MODE:
                world_text = _build_text_world(ents, match_state, velocities)
                blue_names = ", ".join(sorted(k for k in ents if k.startswith("blue")))
                user_prompt = (world_text + f"\n\nCommand: {blue_names}\n\n" +
                               (TEXT_EXPLAIN_INSTRUCTION if is_explain else _text_output_header(len([k for k in ents if k.startswith("blue")]))))
                tokens_limit = 600 if is_explain else 200
            else:
                min_ents = {k: {"x": round(v["x"], 1), "y": round(v["y"], 1)} for k, v in ents.items()}
                
                # B3 experiment: optionally include match_state in the LLM payload
                if os.getenv("R2K_INCLUDE_MATCH_STATE", "0") == "1":
                    if match_state:
                        min_ents["match_state"] = {
                            "status": match_state.get("status", "playing"),
                            "restart_team": match_state.get("restart_team", ""),
                        }
                
                tokens_limit = 600 if is_explain else 150
                req_keys = "Include 'analysis', 'oracle', and 'assignments' keys." if is_explain else "Output ONLY the 'assignments' key."

                # Demo mode: per-bot targets + flat table; non-targeted bots
                # stripped from the snapshot (see _demo_inject_targets)
                if _active_mode == "demo":
                    _demo_inject_targets(min_ents, ents)

                payload = {
                    "model": MODEL_NAME,
                    "prompt": json.dumps(min_ents) + f"\n\nCRITICAL: Output ONLY valid JSON. {req_keys} End immediately after closing bracket.",
                    "system": sys_prompt,
                    "stream": False,
                    "keep_alive": "1h", 
                    "options": {
                        "temperature": 0.0, 
                        "num_predict": tokens_limit,
                        "num_ctx": 4096,
                        "stop": ["<|im_end|>", "<|endoftext|>"] 
                    }
                }
            
            if TEXT_MODE:
                payload = {
                    "model": MODEL_NAME,
                    "prompt": user_prompt,
                    "system": sys_prompt,
                    "stream": False,
                    "keep_alive": "1h", 
                    "options": {
                        "temperature": 0.0, 
                        "num_predict": tokens_limit,
                        "num_ctx": 4096,
                        "stop": ["<|im_end|>", "<|endoftext|>"] 
                    }
                }
            
            payload["stream"] = False
            
            start_t = time.time()
            # FIX 2: Absolut sicherer Timeout für alte CPUs
            resp = requests.post(OLLAMA_URL, json=payload, timeout=150.0)
            lat = int((time.time() - start_t) * 1000)

            if resp.status_code == 200:
                resp_data = resp.json()
                timings = {
                    "prompt_eval_count": resp_data.get("prompt_eval_count"),
                    "eval_count": resp_data.get("eval_count"),
                    "prompt_eval_duration": resp_data.get("prompt_eval_duration", 0),
                    "eval_duration": resp_data.get("eval_duration", 0),
                    "load_duration": resp_data.get("load_duration", 0),
                    "total_duration": resp_data.get("total_duration", 0),
                }
                raw_response = resp_data.get("response", "")
                if TEXT_MODE:
                    # Phase I: text output — regex bot lines, JSON fallback
                    data, err = text_parse(raw_response)
                    if data is None:
                        data, json_err = fast_parse(raw_response)
                        if data is not None:
                            err = 10 + json_err  # JSON fallback after failed text parse
                else:
                    data, err = fast_parse(raw_response)
                
                if data:
                    if "assignments" not in data:
                        data = {"assignments": data}
                    # ONE convention at the bus boundary: the executor's
                    # world-name keys (blue_1) become canon (blue1) so the
                    # bridge's relay-keyed lookups always match — the match-
                    # mode goto fix, live 2026-09-12.
                    data["assignments"] = _canon_assignments(data["assignments"])
                    data["latency_ms"] = lat
                    data["model_name"] = MODEL_NAME
                    if _active_mode == "demo":
                        # Fast-path authority: parked/gesturing bots are
                        # driven ONLY by their fast_cmd — overrides any
                        # executor (mis)assignment for them.
                        _demo_reinject_fast_cmds(data)
                        # Goto persistence: k1_bot is never in the 3B's output
                        # (removed from min_ents), so carry forward any
                        # existing Goto target from the previous write.
                        _persist_non_llm_assignments(data)
                    with open(STRATEGY_PATH + ".tmp", 'w') as f: json.dump(data, f)
                    os.replace(STRATEGY_PATH + ".tmp", STRATEGY_PATH)
                    log_llm_call(world_text if TEXT_MODE else min_ents, sys_prompt, raw_response, 0, lat, tokens_limit, is_explain, timings)
                else:
                    err_preview = raw_response[:150] if raw_response else "EMPTY RESPONSE"
                    print(f"❌ [Parse Error] KI-Antwort zerstört! Rohdaten: {err_preview}", flush=True)
                    log_llm_call(world_text if TEXT_MODE else min_ents, sys_prompt, raw_response, err, lat, tokens_limit, is_explain, timings)
            else:
                print(f"❌ [HTTP Error] Ollama meldet Code: {resp.status_code}", flush=True)
            
            last_mtime = mtime

        # FIX 3: Sauberes Error-Handling ohne Absturz
        except requests.exceptions.ConnectTimeout:
            print("🚨 [Timeout] Kann 127.0.0.1 nicht erreichen (Verbindungsaufbau)!", flush=True)
            time.sleep(1)
        except requests.exceptions.ReadTimeout:
            print("🚨 [Timeout] Ollama rechnet zu lange (> 150s)!", flush=True)
            last_mtime = mtime
        except requests.exceptions.ConnectionError:
            print("🚨 [Connection Refused] Ollama läuft nicht auf 127.0.0.1!", flush=True)
            time.sleep(1)
        except Exception as e:
            print(f"💥 [CRITICAL ERROR] {e}", flush=True)
            traceback.print_exc()
            time.sleep(1)

if __name__ == "__main__":
    main()
