#!/bin/bash
# session_entry.sh — generates a dated stub entry for SESSION_CHANGELOG.md
# Usage: ./docs/session_entry.sh
# Output: prints a markdown stub to stdout. Redirect or paste into the changelog.
#
# The stub captures git facts (date, branch, diff summary, status).
# The agent or human fills in the narrative sections afterwards.

set -euo pipefail

DATE=$(date +%Y-%m-%d)
REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null || echo "")

if [ -z "$REPO_ROOT" ]; then
    echo "ERROR: not inside a git repository" >&2
    exit 1
fi

BRANCH=$(git branch --show-current 2>/dev/null || echo "unknown")

# Tracked files that were modified (staged or unstaged) — excludes untracked
MODIFIED=$(git diff --name-only HEAD 2>/dev/null | sort -u || echo "")
MODIFIED_COUNT=$(echo "$MODIFIED" | grep -c . 2>/dev/null || echo "0")

# Tracked files deleted (no longer on disk)
DELETED=$(git ls-files --deleted 2>/dev/null | sort || echo "")
DELETED_COUNT=$(echo "$DELETED" | grep -c . 2>/dev/null || echo "0")

# New untracked files (exclude directories, exclude common noise)
UNTRACKED=$(git ls-files --others --exclude-standard 2>/dev/null | sort || echo "")
UNTRACKED_COUNT=$(echo "$UNTRACKED" | grep -c . 2>/dev/null || echo "0")

# Last 3 commits (context for what was committed vs uncommitted)
COMMITS=$(git log --oneline -3 2>/dev/null || echo "")

cat << EOF
## ${DATE} — [one-line goal here]

**Goal:** [What was this session for?]

**Done:**
- [What was accomplished. Use file:line evidence for verifiable claims.]

**Files touched:**
EOF

if [ "$MODIFIED_COUNT" -gt 0 ]; then
    echo "$MODIFIED" | sed 's/^/- /'
else
    echo "- (none modified)"
fi

if [ "$UNTRACKED_COUNT" -gt 0 ]; then
    echo ""
    echo "**New files (untracked):**"
    echo "$UNTRACKED" | sed 's/^/- /'
fi

cat << EOF

**Files deleted:**
EOF

if [ "$DELETED_COUNT" -gt 0 ]; then
    echo "$DELETED" | sed 's/^/- /'
else
    echo "- (none)"
fi

cat << EOF

**Not yet done:**
- [Deferred work and why]

**Next:**
- [The single next actionable step]

**Blockers:**
- [Anything that would stop the next session]

---
<!-- Stub generated by session_entry.sh on ${DATE} -->
<!-- Branch: ${BRANCH} | Modified: ${MODIFIED_COUNT} | New: ${UNTRACKED_COUNT} | Deleted: ${DELETED_COUNT} -->
<!-- Last commits:
$(echo "$COMMITS" | sed 's/^/  /')
-->
EOF